apiVersion: v1
kind: Pod
metadata:
  name: left
  annotations:
    opencontrail.org/network: '{"domain": "default-domain", "project": "k8s-default", "name": "k8s-network-left-pod-network"}'
spec:
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]

