apiVersion: v1
kind: Pod
metadata:
  name: right
  annotations:
    opencontrail.org/network: '{"domain": "default-domain", "project": "k8s-default", "name": "k8s-network-right-pod-network"}'
spec:
  containers:
  - name: main
    image: python:2.7-alpine3.9
    workingDir: /root
    command: ["python", "-m", "SimpleHTTPServer", "80"]
    volumeMounts:
    - mountPath: /root/whitelist.html
      name: whitelist
    - mountPath: /root/blacklist.html
      name: blacklist
  volumes:
  - name: whitelist
    hostPath:
      path: /root/whitelist.html
  - name: blacklist
    hostPath:
      path: /root/blacklist.html

